FROM openjdk:8
COPY target/ModuloMantenimiento-1.0.jar /usr/src/ModuloMantenimiento/
WORKDIR /usr/src/ModuloMantenimiento/
CMD ["java","-jar","/usr/src/ModuloMantenimiento/ModuloMantenimiento-1.0.jar"]
